### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by kamicut** [MissingMaps/users#1]
Questions:
- Will it be a problem to keep pinging OSM for the avatars for each user? (Could be a problem on the leaderboard side for all missing maps avatars)
- How do we deal with missing avatars?
- Should we do some caching on the frontend or backend? 

cc @DylanMoriarty @nbumbarger

**Comment by DylanMoriarty** [comment]
We had already planned on having a dummy graphic for those who don't have avatars/gravitars. Just having some standard 'shadow person' image should be sufficient.
