### ISSUE TITLE
Profiles of some users doesn't show after edits

### ISSUE THREAD

**Issue by PanierAvide** [MissingMaps/users#27]
Hello,
I can see that some accounts doesn't appear on Missing Maps users profiles, even after editing on some tasks (for example `#hotosm-project-1487 #aagmapathon #m4r #USAID #PeaceCorps #PCMozambique #AIRSmoz2016 source=Bing #youthmappers #Mapapalooza`) and waiting for like 10 days.
Thank you in advance.

**Comment by dalekunce** [comment]
@PanierAvide right now we are only tracking edits that have #missingmaps included as part of the commit message. We are looking looking into the possibility to look at all edits in the near term.

**Comment by PanierAvide** [comment]
Thanks for your answer. Some of the concerned commits contains `#MissingMaps` (for example `#hotosm-project-1709 #AAGmapathon #KLL #MapGive #MissingMaps #PreparePokhara Source=WorldView-3, DigitalGlobe, NextView, 10 Dec 2015`), is the search case-sensitive ?

**Comment by dalekunce** [comment]
@PanierAvide for this commit we noticed there were some edits being dropped due to some over worked workers. We have deployed some code that should fix it and are rerunning the history to grab any of the dropped edits.

**Comment by PanierAvide** [comment]
OK, thanks for the explanation (and for the great work) :)

**Comment by stev-0** [comment]
This is happening to me too. [This commit ](https://www.openstreetmap.org/changeset/44952721) does not show up in Missing Maps. I also notice that the link between OSM and Missing Maps usernames does not seem to always work - e.g. see here: http://www.missingmaps.org/users/#/2882063
