### ISSUE TITLE
Consistency with the main MissingMaps website

### ISSUE THREAD

**Issue by Omniscimus** [MissingMaps/users#41]
(NOTE: This is essentially the same issue as MissingMaps/users#41, but I experienced the exact same issues here.)

The header on the users module is not consistent with the header on the main website (MissingMaps/missingmaps.github.io#333).

Is this repo kept up to date with some kind of script somehow, or should this be updated manually?

To investigate this, I tried running the users module locally, but I got a blank page when I navigated to it in my browser after running `npm install` and `npm start`. Is this an issue with the project or with my setup?

**Comment by danbjoseph** [comment]
https://github.com/MissingMaps/users/commit/427fee66e19dcfefb2bb8d284ab77e7288478764#diff-6a1559e4b25e80b6a3b7c9c6b7d24db73177617ee8efbc935fae6fd8a59d1667 should update the header to match the main website.

to build locally, please make sure you're running node v6.17.1 (now noted in [.nvmrc](https://github.com/MissingMaps/users/blob/master/.nvmrc))
