### ISSUE TITLE
Vulnerability in `ecstatic`

### ISSUE THREAD

**Issue by kamicut** [MissingMaps/users#46]
There's a vulnerability in `ecstatic@1.4.1` used by `budo@7.1.0`. I think updating budo should fix the vulnerability @dalekunce but we would need to test it.

**Comment by dalekunce** [comment]
#45 updates all the dependencies, there is some changes the react and history that means some of the methods need updating. @maxgrossman volunteered to take a look at it. But more help the merrier.
