### ISSUE TITLE
User Map tiles extend outside its div

### ISSUE THREAD

**Issue by dalekunce** [MissingMaps/users#48]
The new user map appears to have some issues staying in its box.

![screen shot 2018-03-23 at 8 04 14 am](https://user-images.githubusercontent.com/1913857/37836942-2278656c-2e71-11e8-937b-7ec0e54949fc.png)

**Comment by mojodna** [comment]
I can't reproduce this either--what browser are you using / what's the current phase of the moon? The GeoJSON overlay does bounce around when zooming in, but that's internal Leaflet behavior.

**Comment by mojodna** [comment]
This happens when HTTPS is used.
