### ISSUE TITLE
profile pic stopped working

### ISSUE THREAD

**Issue by dalekunce** [MissingMaps/users#49]
The profile pic somehow disappeared after #47 

![screen shot 2018-03-23 at 8 08 19 am](https://user-images.githubusercontent.com/1913857/37837054-7a5153b6-2e71-11e8-94d6-3146ed718a3e.png)

**Comment by mojodna** [comment]
I can't reproduce this:

![image](https://user-images.githubusercontent.com/45/37840169-93989c28-2e79-11e8-8df7-e02e4a3d2ab2.png)

If you see it again, can you look for console messages and paste them in here if they're present?

**Comment by mojodna** [comment]
This happens when using HTTPS.
