### ISSUE TITLE
"invalid date at invalid date"

### ISSUE THREAD

**Issue by danbjoseph** [MissingMaps/users#50]
<img width="339" alt="screen shot 2018-03-24 at 5 33 05 pm" src="https://user-images.githubusercontent.com/4806884/37869178-8406af78-2f89-11e8-9fc4-c69bef3768a1.png">

**Comment by mojodna** [comment]
Which user is this for?

**Comment by danbjoseph** [comment]
Was when looking at mine (danbjoseph)
